#! /bin/bash

REPORTDIR=reports

mkdir -p "${REPORTDIR}"

smilint -s -e -l 6 \
	./EUROVIBES-MIB 2>"${REPORTDIR}/EUROVIBES-MIB.txt"

smilint -s -e -l 6 \
	-p ./EUROVIBES-MIB \
	./EUROVIBES-PROJECTS-MIB 2>"${REPORTDIR}/EUROVIBES-PROJECTS-MIB.txt"

smilint -s -e -l 6 \
	-p ./EUROVIBES-MIB \
	-p ./EUROVIBES-PROJECTS-MIB \
	./EUROVIBES-FBAGENT-MIB 2>"${REPORTDIR}/EUROVIBES-FBAGENT-MIB.txt"

smilint -s -e -l 6 \
	-p ./EUROVIBES-MIB \
	-p ./EUROVIBES-PROJECTS-MIB \
	./EUROVIBES-KLIMA-MIB 2>"${REPORTDIR}/EUROVIBES-KLIMA-MIB.txt"

smilint -s -e -l 6 \
	-p ./EUROVIBES-MIB \
	-p ./EUROVIBES-PROJECTS-MIB \
	./EUROVIBES-BBALARM-MIB 2>"${REPORTDIR}/EUROVIBES-BBALARM-MIB.txt"
